<!-- Begin Footer -->
<br /><br />
<div align="center">
<div align="center" style="border:dashed 1px #999; width:80%;">

	<p style="font-size:xx-small">Copyright &copy; 2008-2011 by Oliver Radwan, Maxwell Palmer, Nolan McNair, Taylor Talmadge, and Allen Tucker.<br />
	<a href="http://sourceforge.net/projects/rmhhomebase/">
	<i>Homebase</i></a>  is free open source software and it comes with absolutely no warranty.  
	      You can redistribute and/or modify this software under the terms of the
	      <br /><a href="http://www.gnu.org/licenses/gpl.html"> GNU General Public License</a>.
	</p>
</div>
</div>
<!-- End Footer -->