<?PHP
	session_start();
	session_cache_expire(30);
?>
<!-- page generated by the BowdoinRMH software package -->
<html>
	<head>
		<title>
			View Personnel
		</title>
		<link rel="stylesheet" href="styles.css" type="text/css" />
	</head>
	<body>
		<div id="container">
			<?PHP include('header.php');?>
			<div id="content">
				<!-- your main page data goes here. This is the place to enter content -->
				<p><strong>View Entries in the Personnel Database</strong><br />
					To find a specific volunteer, <a href="searchPeople.php">search the database</a>!</p>
					<?PHP
						if($_SESSION['access_level']<2){
							//you can only edit your own entry
							echo('<p>You do not have sufficient permissions to view all volunteers. You can <a href="searchPeople.php">search</a> or you can ');
							echo('<a href="personEdit.php?id='.$_SESSION['_id'].'">edit</a> your own profile.</p>');
						}
						else{
						//grab stuff from the db
						include_once('database/dbPersons.php');
						$query_result = getall_persons();
						echo("<p>");

						//the beginnings of not listing all people at once.
						$i=0;
						$num_results = $_GET['num_results'];
						if(!$num_results) $num_results = 25;
						$page_num = $_GET['page_num'];

						$min_num = $num_results*$page_num;
						$max_num = $num_results*($page_num+1);
						if(mysql_num_rows($query_result)<$max_num) $max_num = mysql_num_rows($query_result)+1;
						echo("Viewing results ".($min_num+1)."-".$max_num.". Showing ");

						if($num_results==25)
								echo('<u>25</u> <a href="view.php?page_num=0&num_results=50">50</a> <a href="view.php?page_num=0&num_results=100">100</a>');
						else if($num_results==50)
								echo('<a href="view.php?page_num=0&num_results=25">25</a> <u>50</u> <a href="view.php?page_num=0&num_results=100">100</a>');
						else if($num_results==100)
								echo('<a href="view.php?page_num=0&num_results=25">25</a> <a href="view.php?page_num=0&num_results=50">50</a> <u>100</u>');
						else
								echo('<a href="view.php?page_num=0&num_results=25">25</a> <a href="view.php?page_num=0&num_results=50">50</a> <a href="view.php?page_num=0&num_results=100">100</a>');
						echo(" people per page.</p>");
						echo('<hr size="1" width="30%" align="left">');
						echo('<p><table class="searchResults">');
						while($thisRow = mysql_fetch_array($query_result, MYSQL_ASSOC)){
							if($_SESSION['access_level']<2 && $thisRow['id']=='admin') continue;
							$i++;
							echo("<tr>");
							if($i>=$min_num && $i<$max_num){
								echo('<td class="searchResults" style="padding-right:30px;">'.$thisRow['last_name'].", ".$thisRow['first_name'].'</td>');
								echo('<td class="searchResults"><a href="viewPerson.php?id='.$thisRow['id'].'">view</a></td>');
								echo('<td class="searchResults"><a href="personEdit.php?id='.$thisRow['id'].'">edit</a></td>');
							}
							echo("</tr>");
							echo("\n");
						}
						echo("</table></p>");
						echo('<hr size="1" width="30%" align="left">');
						if($page_num>0) echo("<a href='view.php?page_num=".($page_num-1)."&num_results=".$num_results."'>&lt;&lt; previous ".$num_results."</a> ");
						echo(" ... ");
						if($max_num < $i) echo("<a href='view.php?page_num=".($page_num+1)."&num_results=".$num_results."'>next ".$num_results."&gt&gt</a>");
						}
					?>
				<!-- below is the footer that we're using currently-->
				<?PHP include('footer.inc');?>
			</div>
		</div>
	</body>
</html>
