<?PHP
	session_start();
	session_cache_expire(30);
	include_once('database/dbPersons.php');
    include_once('domain/Person.php');
	$id = $_GET["id"];
	$query_result = retrieve_person($id);
	$person = mysql_fetch_array($query_result, MYSQL_ASSOC);
?>
<!-- page generated by the BowdoinRMH software package -->
<html>
	<head>
		<title>
			Viewing <?PHP echo($person['first_name']." ".$person['last_name']); ?>
		</title>
		<link rel="stylesheet" href="styles.css" type="text/css" />
	</head>
	<body>
		<div id="container">
			<?PHP include('header.php');?>
			<div id="content">
				<?PHP
				 if(!$person){
						//there is no person
						echo('<p id="error">Error: there\'s no person with this id in the database</p>');
						include('footer.inc');
						echo('</div></div></body></html>');
						die();
				}
				else {
					$nice_phone_1 = substr($person['phone1'],0,3)."-".substr($person['phone1'],3,3)."-".substr($person['phone1'],6,4);
					if($person['phone2'])
						$nice_phone_2 = substr($person['phone2'],0,3)."-".substr($person['phone2'],3,3)."-".substr($person['phone2'],6,4);;
					echo("<p>Contact information for " . $person['first_name'] . " " . $person['last_name']."<br />");
					if($_SESSION['_id']==$person['id'] || $_SESSION['access_level']>=2)
						echo("<span style=\"font-size:x-small;\">To view private profile, <a href=\"personEdit.php?id=".$person['id']."\">edit</a>.</span>");
					echo("</p><p>");
					echo("<table class=\"searchResults\"><tr><td colspan=\"2\" class=\"searchResults\">".$person['first_name']." ".$person['last_name']."</td></tr>");
					echo("<tr><td class=\"searchResults\">Phone 1:</td><td class=\"searchResults\">".$nice_phone_1."</td></tr>");
					echo("<tr><td class=\"searchResults\">Phone 2:</td><td class=\"searchResults\">".$nice_phone_2."</td></tr>");
					echo("<tr><td class=\"searchResults\">Email:</td><td class=\"searchResults\"><a href=\"mailto:".$person['email']."\">".$person['email']."</a></td></tr>");
					echo("<tr><td class=\"searchResults\">Status:</td><td class=\"searchResults\">".$person['status']."</td></tr>");
					echo("</table></p>");

					$query = "SELECT id FROM dbShifts WHERE persons LIKE '%".$id."%'";
						 	connect();
						 	$shift_ids = mysql_query($query);
						 	$shifts=array();
						 	if($shift_ids){
						 		while($thisRow = mysql_fetch_array($shift_ids, MYSQL_ASSOC)){

						 			$shift_array = explode("-",$thisRow['id']);

						 			//check if the shift is close enough.
						 			$shift_month = $shift_array[0];
						 			$shift_day = $shift_array[1];
						 			$shift_year = $shift_array[2];

						 			$shift_time_s = $shift_array[3];
						 			$shift_time_e = $shift_array[4];

						 			$cur_month = date("m");
						 			$cur_day = date("d");
						 			$cur_year =	date("y");

						 			if($shift_year > $cur_year)
						 				$shifts[] = $thisRow['id'];
						 			else if($shift_year == $cur_year){
						 				if($cur_month<$shift_month)
						 					$shifts[] = $thisRow['id'];
						 				else if($shift_month == $cur_month){
						 					if($cur_day<=$shift_day){
						 						$shifts[] = $thisRow['id'];
						 					}
						 				}
						 			}
						 		}
						 	}
							if($shifts){
						 		echo('<p>'.$person['first_name'].'\'s Upcoming Schedule:<br />');
						 		echo('<table class="searchResults">');
						 		echo('<tr><td class="searchResults"><strong>Date</strong></td><td class="searchResults"><strong>Time</strong></td></tr>');
						 		foreach($shifts as $tableId){
						 			$shift_array = explode("-",$tableId);
						 			//check if the shift is close enough.
						 			$shift_month = $shift_array[0];
						 			$shift_day = $shift_array[1];
						 			$shift_year = $shift_array[2];

						 			$shift_time_s = $shift_array[3];
						 			$shift_time_e = $shift_array[4];

						 			echo('<tr><td class="searchResults">'.$shift_month.'/'.$shift_day.'/'.$shift_year.'</td>');
						 			echo('<td class="searchResults">'.$shift_time_s.'-'.$shift_time_e.'</td></tr>');
						 		}
							}
							echo('</table></p>');
				}
				?>
				<!-- below is the footer that we're using currently-->
				<?PHP include('footer.inc');?>
			</div>
		</div>
	</body>
</html>
